# --- Data Paths ---
data:
  raw_emails: "machine_learning/data/raw/raw_emails.csv"
  labeled_emails: "machine_learning/data/labeled_emails.csv"
  processed_emails: "machine_learning/data/processed/processed_emails.csv"

# --- Model Paths ---
model:
  logistic_regression: "machine_learning/models/logistic_regression.pkl"
  naive_bayes: "machine_learning/models/naive_bayes.pkl"
  tfidf_vectorizer: "machine_learning/models/tfidf_vectorizer.pkl"

results:
  model_results: "machine_learning/results/model_results.csv"

# --- Training Parameters ---
training:
  test_size: 0.2
  random_state: 42
  tfidf_max_features: 1000
  tfidf_ngram_range: [1, 2]
  logistic_regression_max_iter: 1000
  naive_bayes_alpha: 0.5


# --- API Parameters (when applicable later) ---
# api:
#   host: "127.0.0.1"
#   port: 5000